import type { Project, CaptionStyle } from '../types';

export const CAPTION_PRESETS: Record<string, CaptionStyle> = {
  hormozi: {
    id: 'hormozi',
    name: 'Hormozi Viral',
    fontFamily: 'Montserrat, sans-serif',
    fontSize: 34,
    primaryColor: '#FFFFFF',
    highlightColor: '#FFE600', // Yellow
    outlineColor: '#000000',
    outlineWidth: 4,
    uppercase: true,
    wordsPerChunk: 3,
    animationStyle: 'bounce',
    showEmojis: true,
  },
  mrbeast: {
    id: 'mrbeast',
    name: 'Beast Energy',
    fontFamily: 'Impact, Arial Black, sans-serif',
    fontSize: 38,
    primaryColor: '#FFFFFF',
    highlightColor: '#00FF66', // Neon Green
    outlineColor: '#000000',
    outlineWidth: 5,
    uppercase: true,
    wordsPerChunk: 2,
    animationStyle: 'pop',
    showEmojis: true,
  },
  neon_cyber: {
    id: 'neon_cyber',
    name: 'Neon Cyberpunk',
    fontFamily: 'system-ui, -apple-system, sans-serif',
    fontSize: 32,
    primaryColor: '#E0FFFF',
    highlightColor: '#FF007F', // Neon Pink
    outlineColor: '#1A0033',
    outlineWidth: 4,
    uppercase: true,
    wordsPerChunk: 3,
    animationStyle: 'glow',
    showEmojis: true,
  },
  minimal: {
    id: 'minimal',
    name: 'Clean Minimal',
    fontFamily: 'Inter, system-ui, sans-serif',
    fontSize: 28,
    primaryColor: '#FFFFFF',
    highlightColor: '#38BDF8', // Sky Blue
    outlineColor: '#0F172A',
    outlineWidth: 2,
    uppercase: false,
    wordsPerChunk: 4,
    animationStyle: 'fade',
    showEmojis: false,
  },
};

export const SAMPLE_PROJECTS: Project[] = [
  {
    id: 'proj_hormozi_scale',
    title: 'How to Scale from $0 to $10M (Alex Hormozi Masterclass)',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    sourceType: 'sample',
    duration: 184.0,
    resolution: { width: 1920, height: 1080 },
    status: 'ready',
    allWords: [],
    clips: [
      {
        id: 'clip_1',
        title: 'The #1 Reason 99% of Businesses Fail (Viral Hook)',
        start_time: 2.0,
        end_time: 24.5,
        duration: 22.5,
        virality_score: 98,
        hook_score: 99,
        flow_score: 96,
        virality_reason: 'Opens with a powerful negative belief challenge in the first 2 seconds, followed by high-leverage business clarity and actionable psychology.',
        broll_keywords: ['money growth', 'business strategy', 'success rocket'],
        suggested_emojis: ['💰', '🔥', '🚀', '🧠'],
        summary: 'Breaks down the psychological trap of product diversification before reaching product-market fit.',
        layout: 'auto_track',
        brolls: [
          {
            id: 'broll_1',
            start_time: 6.5,
            end_time: 10.0,
            duration: 3.5,
            query: 'money growth',
            tag: 'money',
            ken_burns_effect: 'zoom_in',
            media_url: 'https://assets.mixkit.co/videos/preview/mixkit-counting-money-bills-41517-large.mp4',
            opacity: 0.95
          },
          {
            id: 'broll_2',
            start_time: 15.0,
            end_time: 18.5,
            duration: 3.5,
            query: 'rocket launch',
            tag: 'scale',
            ken_burns_effect: 'zoom_out',
            media_url: 'https://assets.mixkit.co/videos/preview/mixkit-rocket-taking-off-towards-space-40626-large.mp4',
            opacity: 0.95
          }
        ],
        words: [
          { word: "If", start: 2.0, end: 2.2, speaker: "SPEAKER_00" },
          { word: "you", start: 2.2, end: 2.4, speaker: "SPEAKER_00" },
          { word: "want", start: 2.4, end: 2.7, speaker: "SPEAKER_00" },
          { word: "to", start: 2.7, end: 2.9, speaker: "SPEAKER_00" },
          { word: "build", start: 2.9, end: 3.3, speaker: "SPEAKER_00", emoji: "🔨" },
          { word: "a", start: 3.3, end: 3.4, speaker: "SPEAKER_00" },
          { word: "business", start: 3.4, end: 3.9, speaker: "SPEAKER_00", highlight: true },
          { word: "that", start: 3.9, end: 4.1, speaker: "SPEAKER_00" },
          { word: "actually", start: 4.1, end: 4.6, speaker: "SPEAKER_00" },
          { word: "scales,", start: 4.6, end: 5.2, speaker: "SPEAKER_00", emoji: "🚀" },
          { word: "stop", start: 5.4, end: 5.8, speaker: "SPEAKER_00", highlight: true, emoji: "❌" },
          { word: "launching", start: 5.8, end: 6.3, speaker: "SPEAKER_00" },
          { word: "ten", start: 6.3, end: 6.6, speaker: "SPEAKER_00" },
          { word: "different", start: 6.6, end: 7.1, speaker: "SPEAKER_00" },
          { word: "products", start: 7.1, end: 7.6, speaker: "SPEAKER_00" },
          { word: "at", start: 7.6, end: 7.8, speaker: "SPEAKER_00" },
          { word: "once.", start: 7.8, end: 8.3, speaker: "SPEAKER_00" },
          { word: "The", start: 8.6, end: 8.8, speaker: "SPEAKER_00" },
          { word: "real", start: 8.8, end: 9.1, speaker: "SPEAKER_00" },
          { word: "secret", start: 9.1, end: 9.6, speaker: "SPEAKER_00", highlight: true, emoji: "🤫" },
          { word: "to", start: 9.6, end: 9.8, speaker: "SPEAKER_00" },
          { word: "making", start: 9.8, end: 10.2, speaker: "SPEAKER_00" },
          { word: "millions", start: 10.2, end: 10.8, speaker: "SPEAKER_00", highlight: true, emoji: "💰" },
          { word: "is", start: 10.8, end: 11.0, speaker: "SPEAKER_00" },
          { word: "extreme", start: 11.0, end: 11.5, speaker: "SPEAKER_00" },
          { word: "focus.", start: 11.5, end: 12.1, speaker: "SPEAKER_00", emoji: "🎯" },
          { word: "Pick", start: 12.4, end: 12.7, speaker: "SPEAKER_00" },
          { word: "one", start: 12.7, end: 13.0, speaker: "SPEAKER_00", highlight: true },
          { word: "avatar,", start: 13.0, end: 13.5, speaker: "SPEAKER_00" },
          { word: "one", start: 13.7, end: 14.0, speaker: "SPEAKER_00", highlight: true },
          { word: "core", start: 14.0, end: 14.3, speaker: "SPEAKER_00" },
          { word: "offer,", start: 14.3, end: 14.8, speaker: "SPEAKER_00" },
          { word: "and", start: 15.0, end: 15.2, speaker: "SPEAKER_00" },
          { word: "one", start: 15.2, end: 15.5, speaker: "SPEAKER_00", highlight: true },
          { word: "traffic", start: 15.5, end: 15.9, speaker: "SPEAKER_00" },
          { word: "channel.", start: 15.9, end: 16.5, speaker: "SPEAKER_00", emoji: "📈" },
          { word: "Master", start: 16.8, end: 17.2, speaker: "SPEAKER_00" },
          { word: "that", start: 17.2, end: 17.4, speaker: "SPEAKER_00" },
          { word: "until", start: 17.4, end: 17.7, speaker: "SPEAKER_00" },
          { word: "you", start: 17.7, end: 17.9, speaker: "SPEAKER_00" },
          { word: "hit", start: 17.9, end: 18.2, speaker: "SPEAKER_00" },
          { word: "seven", start: 18.2, end: 18.6, speaker: "SPEAKER_00", highlight: true },
          { word: "figures", start: 18.6, end: 19.1, speaker: "SPEAKER_00", emoji: "💵" },
          { word: "before", start: 19.2, end: 19.6, speaker: "SPEAKER_00" },
          { word: "you", start: 19.6, end: 19.8, speaker: "SPEAKER_00" },
          { word: "even", start: 19.8, end: 20.1, speaker: "SPEAKER_00" },
          { word: "think", start: 20.1, end: 20.4, speaker: "SPEAKER_00" },
          { word: "about", start: 20.4, end: 20.7, speaker: "SPEAKER_00" },
          { word: "expanding.", start: 20.7, end: 21.4, speaker: "SPEAKER_00", emoji: "🔥" },
          { word: "That", start: 21.7, end: 22.0, speaker: "SPEAKER_00" },
          { word: "is", start: 22.0, end: 22.2, speaker: "SPEAKER_00" },
          { word: "how", start: 22.2, end: 22.4, speaker: "SPEAKER_00" },
          { word: "true", start: 22.4, end: 22.8, speaker: "SPEAKER_00" },
          { word: "empires", start: 22.8, end: 23.3, speaker: "SPEAKER_00", highlight: true, emoji: "👑" },
          { word: "are", start: 23.3, end: 23.5, speaker: "SPEAKER_00" },
          { word: "built.", start: 23.5, end: 24.2, speaker: "SPEAKER_00", emoji: "🏆" },
        ]
      },
      {
        id: 'clip_2',
        title: 'Why Charging More Actually Helps Your Customers',
        start_time: 25.0,
        end_time: 46.0,
        duration: 21.0,
        virality_score: 94,
        hook_score: 93,
        flow_score: 95,
        virality_reason: 'Contrarian pricing psychology creates immediate cognitive dissonance and high comment-section debate.',
        broll_keywords: ['money luxury', 'customer success'],
        suggested_emojis: ['🤯', '📈', '💡'],
        summary: 'Pricing higher forces customers to have skin in the game, resulting in 10x higher completion rates.',
        layout: 'auto_track',
        brolls: [
          {
            id: 'broll_3',
            start_time: 30.0,
            end_time: 33.5,
            duration: 3.5,
            query: 'money bills',
            tag: 'money',
            ken_burns_effect: 'zoom_in',
            media_url: 'https://assets.mixkit.co/videos/preview/mixkit-counting-money-bills-41517-large.mp4',
            opacity: 0.95
          }
        ],
        words: [
          { word: "When", start: 25.0, end: 25.3, speaker: "SPEAKER_00" },
          { word: "you", start: 25.3, end: 25.5, speaker: "SPEAKER_00" },
          { word: "raise", start: 25.5, end: 25.9, speaker: "SPEAKER_00", highlight: true },
          { word: "your", start: 25.9, end: 26.1, speaker: "SPEAKER_00" },
          { word: "prices,", start: 26.1, end: 26.6, speaker: "SPEAKER_00", emoji: "💰" },
          { word: "you", start: 26.8, end: 27.0, speaker: "SPEAKER_00" },
          { word: "don't", start: 27.0, end: 27.3, speaker: "SPEAKER_00" },
          { word: "just", start: 27.3, end: 27.5, speaker: "SPEAKER_00" },
          { word: "make", start: 27.5, end: 27.8, speaker: "SPEAKER_00" },
          { word: "more", start: 27.8, end: 28.1, speaker: "SPEAKER_00", highlight: true },
          { word: "profit.", start: 28.1, end: 28.6, speaker: "SPEAKER_00", emoji: "📈" },
          { word: "Your", start: 28.9, end: 29.2, speaker: "SPEAKER_00" },
          { word: "clients", start: 29.2, end: 29.6, speaker: "SPEAKER_00" },
          { word: "get", start: 29.6, end: 29.8, speaker: "SPEAKER_00" },
          { word: "dramatically", start: 29.8, end: 30.5, speaker: "SPEAKER_00" },
          { word: "better", start: 30.5, end: 30.9, speaker: "SPEAKER_00", highlight: true },
          { word: "results.", start: 30.9, end: 31.5, speaker: "SPEAKER_00", emoji: "🏆" },
          { word: "People", start: 31.8, end: 32.2, speaker: "SPEAKER_00" },
          { word: "who", start: 32.2, end: 32.4, speaker: "SPEAKER_00" },
          { word: "pay", start: 32.4, end: 32.7, speaker: "SPEAKER_00" },
          { word: "more,", start: 32.7, end: 33.1, speaker: "SPEAKER_00" },
          { word: "pay", start: 33.3, end: 33.6, speaker: "SPEAKER_00", highlight: true },
          { word: "more", start: 33.6, end: 33.9, speaker: "SPEAKER_00" },
          { word: "attention.", start: 33.9, end: 34.6, speaker: "SPEAKER_00", emoji: "🧠" },
        ]
      }
    ]
  }
];
